name: terraform deployment
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v4
      - name: setup terraform binary
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.3
      - name: Terraform init, plan
        run: |
          terraform init
          terraform plan
      - name: Terraform apply
        run: terraform apply -auto-approve

        
  
